// <auto-generated />
using System;
using Booble_IA_API._3___Repository.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Booble_IA_API.Migrations
{
    [DbContext(typeof(BoobleContext))]
    partial class BoobleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Booble_IA_API._3___Repository.Entities.Usuario", b =>
                {
                    b.Property<int>("Idf_Usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Idf_Usuario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Idf_Usuario"));

                    b.Property<string>("Des_Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("Des_Email");

                    b.Property<string>("Des_Nme")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Des_Nme");

                    b.Property<DateTime>("Dta_Alteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Dta_Alteracao");

                    b.Property<DateTime>("Dta_Cadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Dta_Cadastro")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("Flg_Sexo")
                        .HasColumnType("boolean")
                        .HasColumnName("Flg_Sexo");

                    b.Property<string>("Num_Telefone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("Num_Telefone");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Senha");

                    b.HasKey("Idf_Usuario");

                    b.ToTable("TAB_Usuario", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
